# AUTO-GENERATED by gen_cityscapes_configs.py -- DO NOT EDIT BY HAND.
# Cityscapes UPerNet, 80k @ 512x1024. Backbone: flash_swin_adaptive, window 32, patch 2.
# token-density effect at matched window 32
#
# ADAPTIVE variant is required: the crop is non-square and LocalSwinBackbone's fixed
# path would silently resize 512x1024 -> 512x512. See gen_cityscapes_configs.py.
_base_ = [
    '../../../../configs/_base_/models/upernet_swin.py',
    '../../../../configs/_base_/datasets/cityscapes.py',
    '../../../../configs/_base_/default_runtime.py',
    '../../../../configs/_base_/schedules/schedule_80k.py',
]

custom_imports = dict(imports=['projects.local_backbones'], allow_failed_imports=False)

crop_size = (512, 1024)
data_preprocessor = dict(size=crop_size)

model = dict(
    data_preprocessor=data_preprocessor,
    backbone=dict(
        _delete_=True,
        type='LocalSwinBackbone',
        variant='flash_swin',
        img_size=512,
        patch_size=2,
        in_chans=3,
        embed_dim=96,
        depths=(2, 2, 6, 2),
        num_heads=(3, 6, 12, 24),
        window_size=32,
        mlp_ratio=4.0,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.2,
        ape=False,
        patch_norm=True,
        use_checkpoint=True,
        fused_window_process=False,
        pretrained_window_sizes=(0, 0, 0, 0),
        out_indices=(0, 1, 2, 3),
        out_norm=True,
        checkpoint_path='/path/to/scratch',
        strict_load=False,
        swin_root='/path/to',
    ),
    decode_head=dict(in_channels=[96, 192, 384, 768], num_classes=19),
    auxiliary_head=dict(in_channels=384, num_classes=19),
)

# Identical to the ADE20K table_seg optimiser, schedule end swapped to 80k.
optim_wrapper = dict(
    _delete_=True,
    type='OptimWrapper',
    accumulative_counts=2,
    optimizer=dict(
        type='AdamW', lr=0.00012, betas=(0.9, 0.999), weight_decay=0.01),
    paramwise_cfg=dict(
        custom_keys={
            'absolute_pos_embed': dict(decay_mult=0.),
            'relative_position_bias_table': dict(decay_mult=0.),
            'norm': dict(decay_mult=0.)
        }))

param_scheduler = [
    dict(type='LinearLR', start_factor=1e-6, by_epoch=False, begin=0, end=1500),
    dict(type='PolyLR', eta_min=0.0, power=1.0, begin=1500, end=80000,
         by_epoch=False),
]

train_dataloader = dict(batch_size=2)
val_dataloader = dict(batch_size=1)
test_dataloader = val_dataloader

train_cfg = dict(type='IterBasedTrainLoop', max_iters=80000, val_interval=8000)
val_cfg = dict(type='ValLoop')
val_evaluator = dict(type='IoUMetric', iou_metrics=['mIoU'])
test_evaluator = val_evaluator
